scrape_configs:
  - job_name: 'core-api'
    static_configs:
      - targets: ['core-api.default.svc.cluster.local:9100']
    metrics_path: /metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter.default.svc.cluster.local:9187']

